spring:

#  MYSQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.76.27.208/yeargun
    username: root


#    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
#    #    mysql://${DB_HOST}/${DB_NAME}?useSSL=false
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect